services:

  api:
    build: .

    container_name: marin-api

    ports:
      - "9000:9000"

    restart: unless-stopped

    environment:
      NODE_ENV: production

    # optional but recommended for stability
    init: true




